{% set PKG_NAME = 'arduino-slow-soft-wire' %}
{% set LIB_NAME = 'SlowSoftWire' %}
{% set VERSION = '1.0.1' %}
source:
  url: https://github.com/sci-bots/{{ LIB_NAME }}/archive/v{{ VERSION }}.tar.gz

package:
  name: {{ PKG_NAME }}
  version: {{ VERSION }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 2
  script:
    python -c
      "import os.path; import os; import shutil;
      CONDA_LIB_INC = os.environ.get('LIBRARY_INC',
                                     os.path.join(os.environ['PREFIX'],
                                                  'include'));
      install_dir = os.path.join(CONDA_LIB_INC, 'Arduino', '{{ LIB_NAME }}');
      shutil.copytree(os.environ['SRC_DIR'], install_dir);
      BUILD_SCRIPT = os.path.join(install_dir, 'bld.bat');
      BUILD_SCRIPT = BUILD_SCRIPT if os.path.isfile(BUILD_SCRIPT) else os.path.join(install_dir, 'build.sh');
      os.remove(BUILD_SCRIPT);
      "

requirements:
  build:
    - python

  run:
    - arduino-slow-soft-i2c-master

about:
  home: https://github.com/sci-bots/{{ LIB_NAME }}
  license: LGPL
