source:
  git_url: https://github.com/sci-bots/SlowSoftWire

package:
  name: arduino-slow-soft-wire
  version: 1.0.0

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
