{% set PKG_NAME = 'arduino-slow-soft-wire' %}
{% set LIB_NAME = 'SlowSoftWire' %}
{% set VERSION = '1.0.1' %}
source:
  url: https://github.com/sci-bots/{{ LIB_NAME }}/archive/v{{ VERSION }}.tar.gz
  fn: {{ LIB_NAME }}-v{{ VERSION }}.tar.gz

package:
  name: {{ PKG_NAME }}
  version: {{ VERSION }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 5
  noarch: generic
  script:
    python -c
      "import os.path; import os; import shutil; import platformio_helpers as pioh;
      install_dir = pioh.conda_arduino_include_path().joinpath('{{ LIB_NAME }}');
      shutil.copytree(os.environ['SRC_DIR'], install_dir);
      BUILD_SCRIPT = os.path.join(install_dir, 'bld.bat');
      BUILD_SCRIPT = BUILD_SCRIPT if os.path.isfile(BUILD_SCRIPT) else os.path.join(install_dir, 'build.sh');
      os.remove(BUILD_SCRIPT);
      "

requirements:
  build:
    - platformio-helpers >=0.6
    - python

  run:
    - arduino-slow-soft-i2c-master

about:
  home: https://github.com/sci-bots/{{ LIB_NAME }}
  license: LGPL
