source:
  git_url: https://github.com/sci-bots/SlowSoftWire

package:
  name: arduino-slow-soft-wire
{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.post{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.0
{% endif %}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  run:
    - arduino-slow-soft-i2c-master

about:
  home: https://github.com/sci-bots/SlowSoftWire
  license: LGPL
